### ISSUE TITLE
Returns incorrect external IP

### ISSUE THREAD

**Issue by inspiredearth** [alexchantastic/alfred-ip-address-workflow#11]
For as long as I can recall (a year or more), the workflow doesn’t return my correct external IP.

It comes back with the following:
![image](https://user-images.githubusercontent.com/667395/172567109-29df465d-ecf1-4fb4-bf65-7e0b37ff7763.png)

I am located in New Zealand. That IP address is from a broadband connection on the COX network, in the USA.
https://www.ip-tracker.org/lookup.php?ip=184.189.4.152

Any suggestions as to why it doesn’t come back with my correct external IP?

**Comment by alexchantastic** [comment]
That's odd! I don't know exactly why that would be the case. The workflow uses an external service to discern your external IP.

Do you get the same (incorrect) IP when you visit https://icanhazip.com/ directly?

**Comment by inspiredearth** [comment]
Yes, same incorrect IP comes up.

I’ve discovered what the issue is. I use DNS servers from a service called Getflix. It should only impact my apparent IP when I am accessing services like Netflix, Amazon Prime Video, and a range of US streaming services.

It seems that for some reason when I am using Getflix DNS servers, that particular IP lookup server (icanhazip) returns a US IP address.

I’ve not seen that occurring when I use numerous other online external IP services (like whatismyip, and others). Seems there’s something about the icanhazip service that triggers Getflix into (wrongly) determining it’s a request from Amazon, Netflix, etc.

So it seems we can close this issue. 

I appreciate your quick response.

**Comment by alexchantastic** [comment]
Thanks for debugging! Previously, this workflow used https://ifconfig.co/ as the external service. If that displays the correct IP, can just swap out the URLs (or just roll back to [v1.1.1](https://github.com/alexchantastic/alfred-ip-address-workflow/releases/tag/v1.1.1)).

I may switch to https://whatismyip.akamai.com which seems to have better response times. Let me know if that returns the correct IP for you.

**Comment by inspiredearth** [comment]
Hi Alex …

This reports my correct IP — icanhazip.com <http://icanhazip.com/> — as does whatismyip.

I’ll switch it out for icanhazip.com <http://icanhazip.com/>

Thanks very mch.

Jonathan

**Comment by alexchantastic** [comment]
The [v1.2.0](https://github.com/alexchantastic/alfred-ip-address-workflow/releases/tag/v1.2.0) release adds a user configuration option to easily change the external IP service. Please refer to instructions in the [README](https://github.com/alexchantastic/alfred-ip-address-workflow#external-ip-services) on how to leverage this option.
