### ISSUE TITLE
Doesn't work anymore (could be because of Big Sur?)

### ISSUE THREAD

**Issue by raviriley** [alexchantastic/alfred-ip-address-workflow#7]
![ipworkflow doesnt work](https://user-images.githubusercontent.com/8132955/116493692-1819df00-a854-11eb-8141-5c958b227d5d.gif)

**Comment by alexchantastic** [comment]
Looks like ipconfig.co changed how accessing their API which broke the script. This should be fixed in latest release: https://github.com/alexchantastic/alfred-ip-address-workflow/releases/tag/v1.1.1.
