### ISSUE TITLE
Error with ifconfig.co

### ISSUE THREAD

**Issue by juniorsaldanha** [alexchantastic/alfred-ip-address-workflow#8]
ifconfig.co isnt working, i recommend change to ifconfig.me/ip ...

**Comment by alexchantastic** [comment]
ifconfig.co seems to work for me just fine. Can you outline the error you are getting?

**Comment by juniorsaldanha** [comment]
Maybe is my location, im in South America, Brazil, perhaps you could put both, in case one is not working in the user's locale.
![image](https://user-images.githubusercontent.com/30378044/151858948-e5b6de7b-0329-405c-bbca-73a1e56ec21b.png)

**Comment by alexchantastic** [comment]
The [v1.1.2](https://github.com/alexchantastic/alfred-ip-address-workflow/releases/tag/v1.1.2) release now uses icanhazip.com to retrieve external IPs.
