### ISSUE TITLE
Why i can't get ip address when I input "ip"

### ISSUE THREAD

**Issue by shenhaoguangDayDayUp** [alexchantastic/alfred-ip-address-workflow#9]
<img width="964" alt="图片" src="https://user-images.githubusercontent.com/17617821/149860068-0ae088a0-349d-4d19-9d7b-1247a569a15c.png">

**Comment by shenhaoguangDayDayUp** [comment]
<img width="811" alt="图片" src="https://user-images.githubusercontent.com/17617821/149860208-58341050-eeb6-4c10-918e-1f9830f8299c.png">

**Comment by alexchantastic** [comment]
Please update to the latest release: [v1.1.1](https://github.com/alexchantastic/alfred-ip-address-workflow/releases/tag/v1.1.1)

**Comment by shenhaoguangDayDayUp** [comment]
> Please update to the latest release: [v1.1.1](https://github.com/alexchantastic/alfred-ip-address-workflow/releases/tag/v1.1.1)

<img width="942" alt="图片" src="https://user-images.githubusercontent.com/17617821/149877266-e2f09d17-da01-411a-8d03-8eacb1046fe2.png">
<img width="446" alt="图片" src="https://user-images.githubusercontent.com/17617821/149877450-a2f10a45-727e-4c7a-af1c-5fddf0c26e28.png">

 I was updated,but sitll can't .

**Comment by alexchantastic** [comment]
Are you able to access https://ifconfig.co?
